"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from decimal import Decimal
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Previously this compared os.getenv(...).lower() == 'True', which can never
# match -- DEBUG was permanently False regardless of the env var.
DEBUG = os.getenv('DEBUG', 'False').strip().lower() in {'true', '1', 'yes', 'on'}

# SECURITY WARNING: keep the secret key used in production secret!
# The key is read from the environment only; it is never committed to the repo.
SECRET_KEY = os.getenv('SECRET_KEY', '').strip()
_PLACEHOLDER_SECRETS = {'', 'your-django-secret-key-here', 'changeme'}
if SECRET_KEY.lower() in _PLACEHOLDER_SECRETS:
    if not DEBUG:
        raise ImproperlyConfigured(
            'SECRET_KEY must be set to a real value in the environment. '
            'Generate one with: python -c "import secrets; print(secrets.token_urlsafe(64))"'
        )
    SECRET_KEY = 'django-insecure-development-only-do-not-use-in-production'

# The Render host is always accepted so the service answers on its canonical
# URL; DJANGO_ALLOWED_HOSTS *extends* this list for custom/staging domains.
_RENDER_HOST = 'forex-trader-backend.onrender.com'
_extra_allowed_hosts = [
    host.strip()
    for host in os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',')
    if host.strip()
]
ALLOWED_HOSTS = list(
    dict.fromkeys([_RENDER_HOST, 'localhost', '127.0.0.1', *_extra_allowed_hosts])
)
if not DEBUG and not _extra_allowed_hosts:
    raise ImproperlyConfigured(
        'DJANGO_ALLOWED_HOSTS must list the real hostnames in production.'
    )


# ===========================
# Email Configuration
# ===========================
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '465'))
EMAIL_HOST_USER = os.getenv('EMAIL_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASSWORD', '')
EMAIL_USE_SSL = os.getenv('EMAIL_SECURE', 'true').lower() == 'true'
EMAIL_USE_TLS = os.getenv('EMAIL_TLS', 'false').lower() == 'true'
DEFAULT_FROM_EMAIL = os.getenv('EMAIL_GENERAL', EMAIL_HOST_USER)
ADMIN_PANEL_URL = os.getenv('ADMIN_PANEL_URL', '')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'forex',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
]

MIDDLEWARE = [
    # CorsMiddleware must sit above anything that can generate a response,
    # otherwise a preflight (OPTIONS) short-circuits before the CORS headers
    # are attached and the browser reports "No 'Access-Control-Allow-Origin'".
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    # Fail closed: a view without an explicit decorator is never public.
    # The handful of genuinely public endpoints opt out with @permission_classes([AllowAny]).
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'forex.authentication.BearerTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.getenv('THROTTLE_ANON', '60/hour'),
        'user': os.getenv('THROTTLE_USER', '600/hour'),
    },
}

# Explicit origin allowlist -- never CORS_ALLOW_ALL_ORIGINS in production.
# Defaults cover the Vercel deployment plus the CRA (3000) and Vite (5173)
# dev servers; override CORS_ALLOWED_ORIGINS to change them without a code deploy.
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        'CORS_ALLOWED_ORIGINS',
        'https://forex-trader-frontend.vercel.app,'
        'http://localhost:3000,'
        'http://localhost:5173',
    ).split(',')
    if origin.strip()
]
# The frontend authenticates with `Authorization: Bearer <token>`, and
# CORS_ALLOW_CREDENTIALS covers the session-cookie path.
CORS_ALLOW_CREDENTIALS = True
# Listed explicitly (matching the library default) so the Authorization header
# the API client sends can never silently stop being allowed.
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Needed for any session-authenticated call; must include the scheme.
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        'CSRF_TRUSTED_ORIGINS',
        'https://forex-trader-frontend.vercel.app,'
        'http://localhost:3000,'
        'http://localhost:5173',
    ).split(',')
    if origin.strip()
]

# Hardening applied whenever DEBUG is off (i.e. any real deployment).
if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True').lower() == 'true'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    X_FRAME_OPTIONS = 'DENY'

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + str(BASE_DIR / 'db.sqlite3'),
    )
}
_db_engine = str(DATABASES['default'].get('ENGINE') or '')
# SQLite has no row-level locking, so select_for_update() silently does
# nothing. A money app must never fall back to it unnoticed. (dj_database_url
# returns an empty dict when DATABASE_URL is set but blank, hence the "" case.)
if not DEBUG and (not _db_engine or _db_engine.endswith('sqlite3')):
    raise ImproperlyConfigured(
        'DATABASE_URL must point at a real database in production; '
        'refusing to fall back to SQLite.'
    )



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Uploaded files (e.g. KYC documents)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Paystack (Nigeria payment gateway)
PAYSTACK_PUBLIC_KEY = os.getenv('PAYSTACK_PUBLIC_KEY', '')
PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY', '')
PAYSTACK_BASE_URL = os.getenv('PAYSTACK_BASE_URL', 'https://api.paystack.co')
if not DEBUG and (
    not PAYSTACK_SECRET_KEY or PAYSTACK_SECRET_KEY.startswith('sk_test_')
):
    raise ImproperlyConfigured(
        'PAYSTACK_SECRET_KEY must be set to a live secret key in production.'
    )

# Service charges (percentage fees deducted from funding and withdrawals)
# Money is handled as Decimal end-to-end; never float.
FUNDING_FEE_PERCENT = Decimal(os.getenv('FUNDING_FEE_PERCENT', '1.5'))
WITHDRAWAL_FEE_PERCENT = Decimal(os.getenv('WITHDRAWAL_FEE_PERCENT', '1.5'))
MIN_WITHDRAWAL = Decimal(os.getenv('MIN_WITHDRAWAL', '1000'))

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Deriv API Configuration
DERIV_API_TOKEN = os.getenv('DERIV_API_TOKEN')
DERIV_API_URL = os.getenv('DERIV_API_URL', 'wss://ws.binaryws.com/websockets/v3')
DERIV_APP_ID = os.getenv('DERIV_APP_ID', '1089')

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
