# Generated by Django 4.2.23 on 2025-09-24 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('deriv_symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DerivAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=50, unique=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_demo', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('PENDING', 'Pending')], default='OPEN', max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=6, max_digits=12)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deriv_contract_id', models.CharField(blank=True, max_length=50, null=True)),
                ('deriv_transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('currency_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.currencypair')),
            ],
            options={
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['status', '-opened_at'], name='forex_trade_status_0ca2c5_idx'), models.Index(fields=['currency_pair', '-opened_at'], name='forex_trade_currenc_046a84_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.DecimalField(decimal_places=6, max_digits=12)),
                ('ask_price', models.DecimalField(decimal_places=6, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('currency_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.currencypair')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['currency_pair', '-timestamp'], name='forex_price_currenc_39c61b_idx')],
            },
        ),
    ]
